const fs = require('fs')
const path = require('path')
const yaml = require('js-yaml')

const CONFIG_DIR = path.join(process.cwd(), 'config')
const OUTPUT_DIR = path.join(process.cwd(), 'src', 'data', 'generated')

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true })
}

function loadYamlFile(filename) {
  const filePath = path.join(CONFIG_DIR, filename)
  const fileContents = fs.readFileSync(filePath, 'utf8')
  return yaml.load(fileContents)
}

function generateTsFile(name, data) {
  const outputPath = path.join(OUTPUT_DIR, `${name}.ts`)
  const content = `// Auto-generated from config/${name}.yml
// DO NOT EDIT THIS FILE MANUALLY - Edit the YAML file instead

export const ${name.toUpperCase()}_CONFIG = ${JSON.stringify(data, null, 2)} as const
`
  fs.writeFileSync(outputPath, content)
  console.log(`✓ Generated ${name}.ts`)
}

// Load and generate all configs
try {
  const personal = loadYamlFile('personal.yml')
  const projects = loadYamlFile('projects.yml')
  const terminal = loadYamlFile('terminal.yml')

  generateTsFile('personal', personal)
  generateTsFile('projects', projects)
  generateTsFile('terminal', terminal)

  console.log('\n✅ All config files generated successfully!')
} catch (error) {
  console.error('❌ Error generating config files:', error.message)
  process.exit(1)
}
